Keep empty tables after AVRO copy stage
Based on feedback from one of our customers, we decided to keep emtpy tables after AVRO copy stage. This is mainly for supporting cases were first a VCF file is imported and then we keep appending new rows to the newly created tables by running Variant Transforms with `--append` flag. In this case, if the first VCF file does not have variants in all chromosome we should still keep all empty output tables, so append operation will be possible. Otherwise the append run will fail due to the following check:

ValueError: Table PROJECT_ID:DATASET_IT.BASE_TABLE_ID__chrXX does not exist, cannot append to it.

Where `chrXX` is the empty table in the fist run.

Note, this PR is technically rollsback the change in #596